'use client';
import { Search, X, ChevronRight, Building2, ArrowUpRight } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import {Empty as EmptyPrimitive,EmptyHeader,EmptyTitle,EmptyMedia} from '@/components/ui/empty';
import type { Project, Task } from './data';
export const today='2026-09-10';
export const money=(n:number)=>n.toLocaleString('th-TH',{maximumFractionDigits:2});
export const date=(s:string|null)=>s?new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00')):'ยังไม่กำหนด';
export const overdue=(t:Task)=>!!t.due&&t.due<today&&!['เสร็จแล้ว','พักงาน'].includes(t.status);
export const stageLabel=(s:string)=>({'Pre 1':'ออกแบบเบื้องต้น','Pre 2':'พัฒนาแบบ','Pre 3':'สรุปแบบ','Final':'แบบขั้นสุดท้าย','Drawing':'เขียนแบบก่อสร้าง','Draw Struc':'แบบโครงสร้าง','BOQ':'ประมาณราคา','Con':'สำรวจหน้างาน','TOR':'กำหนดขอบเขต'}[s]||s);
export function Avatar({name,small=false}:{name:string;small?:boolean}){return <span className={`avatar ${['mint','blue','purple','orange'][(name.charCodeAt(0)||0)%4]} ${small?'small':''}`} title={name}>{name.replace(/น้อง|พี่/g,'').slice(0,2)}</span>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}><i/>{children}</span>}
export function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[];label:string}){return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger className="choice" aria-label={label}><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>}
export function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <div className="search-box"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button onClick={()=>onChange('')} aria-label="ล้างคำค้น"><X size={16}/></button>}</div>}
export function Empty({text,action,label='ล้างตัวกรอง'}:{text:string;action?:()=>void;label?:string}){return <EmptyPrimitive className="empty-state"><EmptyHeader><EmptyMedia><Search/></EmptyMedia><EmptyTitle>{text}</EmptyTitle></EmptyHeader>{action&&<Button variant="outline" onClick={action}>{label}</Button>}</EmptyPrimitive>}
export function Stat({label,value,unit,icon,note,action,accent}:{label:string;value:string;unit:string;icon:React.ReactNode;note:string;action:()=>void;accent:string}){return <button className={`stat-card ${accent}`} onClick={action}><div className="stat-top"><span>{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value">{value}<span>{unit}</span></div><div className="stat-note">{note}<ArrowUpRight size={15}/></div></button>}
export function ProjectTable({items,show}:{items:Project[];show:(id:string)=>void}){return <div className="project-table"><Table><TableHeader><TableRow><TableHead>โครงการ</TableHead><TableHead>ระยะงาน</TableHead><TableHead>ผู้รับผิดชอบ</TableHead><TableHead>กำหนดส่งเดิม</TableHead><TableHead>สถานะ</TableHead><TableHead><span className="sr-only">เปิด</span></TableHead></TableRow></TableHeader><TableBody>{items.map(p=><TableRow key={p.id}><TableCell><button className="project-name" onClick={()=>show(p.id)}><span className="project-icon"><Building2 size={19}/></span><span><strong>{p.name}</strong><small>{p.id} · {p.month==='2026-09'?'แผนเดือนกันยายน':p.month}</small></span></button></TableCell><TableCell><span className="stage"><i/>{stageLabel(p.stage)}</span></TableCell><TableCell><span className="person"><Avatar name={p.owner} small/>{p.owner}</span></TableCell><TableCell className={p.due&&p.due<today&&p.status!=='พักงาน'?'date-warn':''}>{date(p.due)}</TableCell><TableCell><Badge tone={p.status==='พักงาน'?'amber':p.status==='ดำเนินการ'?'green':'neutral'}>{p.status}</Badge></TableCell><TableCell><button className="icon-button" aria-label={'เปิด '+p.name} onClick={()=>show(p.id)}><ChevronRight size={18}/></button></TableCell></TableRow>)}</TableBody></Table>{!items.length&&<Empty text="ไม่พบโครงการที่ตรงกับตัวกรอง"/>}</div>}
